version: "3.7"

services:

  nodejs-server:
    build: 
      context: "."
    ports:
      - "3333:3333"
    container_name: soccer-api
    volumes:
      - '.:/app'
      - '/app/node_modules'

  mysql:
      container_name: mysql-image
      image: mysql:5.7
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "secret"
        MYSQL_DATABASE: "soccer"
      volumes:
          - persist:/var/lib/mysql

volumes:
    persist: